package org.commcare.app.oracle

import org.commcare.app.engine.FormSerializer
import org.javarosa.core.model.FormDef
import org.javarosa.core.model.data.IAnswerData
import org.javarosa.form.api.FormEntryController
import org.javarosa.form.api.FormEntryModel
import org.javarosa.xform.util.XFormUtils
import java.io.InputStream

/**
 * Oracle test runner that loads XForm fixtures, fills them with predetermined answers,
 * serializes the output via our cross-platform FormSerializer, and compares against
 * expected output generated by the JVM engine's XFormSerializingVisitor.
 *
 * This validates that our commonMain serialization path produces correct XML.
 */
class OracleTestRunner {

    /**
     * Load a form from classpath, fill it with answers, and return the serialized XML.
     * Answers are provided as a list of IAnswerData in question order.
     */
    private fun loadForm(formResource: String): FormDef? {
        val stream: InputStream = this::class.java.getResourceAsStream(formResource)
            ?: return null
        return XFormUtils.getFormFromInputStream(stream)
    }

    fun fillAndSerialize(formResource: String, answers: List<IAnswerData?>): FormResult {
        val formDef = loadForm(formResource)
            ?: return FormResult.Error("Could not load form: $formResource")

        formDef.initialize(true, null)

        val model = FormEntryModel(formDef)
        val controller = FormEntryController(model)

        // Step through form, applying answers in order
        controller.stepToNextEvent()
        var answerIndex = 0

        while (model.getEvent() != FormEntryController.EVENT_END_OF_FORM) {
            if (model.getEvent() == FormEntryController.EVENT_QUESTION) {
                if (answerIndex < answers.size && answers[answerIndex] != null) {
                    val result = controller.answerQuestion(answers[answerIndex])
                    if (result != FormEntryController.ANSWER_OK) {
                        return FormResult.Error(
                            "Answer rejected at question $answerIndex: result=$result"
                        )
                    }
                }
                answerIndex++
            }
            controller.stepToNextEvent()
        }

        // Serialize using our cross-platform serializer
        return try {
            val xml = FormSerializer.serializeForm(formDef)
            FormResult.Success(xml, formDef)
        } catch (e: Exception) {
            FormResult.Error("Serialization failed: ${e.message}")
        }
    }

    /**
     * Compare our cross-platform serialization against the JVM-only XFormSerializingVisitor.
     */
    fun compareSerializers(formResource: String, answers: List<IAnswerData?>): ComparisonResult {
        val formDef = loadForm(formResource)
            ?: return ComparisonResult.Error("Could not load form: $formResource")

        formDef.initialize(true, null)

        val model = FormEntryModel(formDef)
        val controller = FormEntryController(model)

        // Fill form
        controller.stepToNextEvent()
        var answerIndex = 0
        while (model.getEvent() != FormEntryController.EVENT_END_OF_FORM) {
            if (model.getEvent() == FormEntryController.EVENT_QUESTION) {
                if (answerIndex < answers.size && answers[answerIndex] != null) {
                    controller.answerQuestion(answers[answerIndex])
                }
                answerIndex++
            }
            controller.stepToNextEvent()
        }

        // Our cross-platform serializer
        val ourXml = try {
            FormSerializer.serializeForm(formDef)
        } catch (e: Exception) {
            return ComparisonResult.Error("Our serializer failed: ${e.message}")
        }

        // JVM-only serializer (oracle)
        val oracleXml = try {
            val visitor = org.javarosa.model.xform.XFormSerializingVisitor()
            val bytes = visitor.serializeInstance(formDef.getInstance()!!)
            String(bytes, Charsets.UTF_8)
        } catch (e: Exception) {
            return ComparisonResult.Error("Oracle serializer failed: ${e.message}")
        }

        val ourNorm = normalizeXml(ourXml)
        val oracleNorm = normalizeXml(oracleXml)

        return if (ourNorm == oracleNorm) {
            ComparisonResult.Match(ourXml, oracleXml)
        } else {
            ComparisonResult.Mismatch(ourXml, oracleXml)
        }
    }

    /**
     * Normalize XML for comparison: trim whitespace, normalize line endings.
     */
    private fun normalizeXml(xml: String): String {
        return xml.trim()
            .replace("\r\n", "\n")
            .replace("\r", "\n")
            .lines()
            .joinToString("\n") { it.trim() }
    }
}

sealed class FormResult {
    data class Success(val xml: String, val formDef: FormDef) : FormResult()
    data class Error(val message: String) : FormResult()
}

sealed class ComparisonResult {
    data class Match(val ourXml: String, val oracleXml: String) : ComparisonResult()
    data class Mismatch(val ourXml: String, val oracleXml: String) : ComparisonResult()
    data class Error(val message: String) : ComparisonResult()
}
