package org.javarosa.core.model.data

import org.javarosa.core.util.externalizable.Externalizable

/**
 * An IAnswerData object represents an answer to a question
 * posed to a user.
 *
 * IAnswerData objects should never in any circumstances contain
 * a null data value. In cases of empty or non-existent responses,
 * the IAnswerData reference should itself be null.
 *
 * @author Drew Roos
 */
interface IAnswerData : Externalizable {
    /**
     * @param o the value of this answerdata object. Cannot be null.
     *          Null Data will not overwrite existing values.
     * @throws NullPointerException if o is null
     */
    fun setValue(o: Any?) // can't be null

    /**
     * @return The value of this answer, will never
     * be null
     */
    fun getValue(): Any? // will never be null

    /**
     * @return Gets a string representation of this
     * answer
     */
    fun getDisplayText(): String?

    fun clone(): IAnswerData?

    /**
     * Data types can be uncast if they are expected to be used
     * in different contexts. This allows, for instance, select
     * values to be generated by casting other types or vic-a-versa.
     *
     * @return An uncast representation of this answer which can
     * be used in a different context.
     */
    fun uncast(): UncastData

    /**
     * Casts the provided data into this data type.
     *
     * @param data An uncast data value which is compatible
     *             with this data type
     * @return An instance of the instance's data type
     * which contains that value
     * @throws IllegalArgumentException If the uncast data is
     *                                  not in a compatible format
     */
    @Throws(IllegalArgumentException::class)
    fun cast(data: UncastData): IAnswerData?
}
