name: CommCare
options:
  bundleIdPrefix: org.marshellis.commcare
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.4"
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  CommCare:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        type: group
      - path: iosApp/Assets.xcassets
    dependencies:
      - sdk: libsqlite3.tbd
    settings:
      base:
        INFOPLIST_FILE: iosApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: org.marshellis.commcare.ios
        OTHER_LINKER_FLAGS:
          - "$(inherited)"
          - "-framework"
          - "CommCareApp"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: 6GY92LKY29
      configs:
        Debug:
          FRAMEWORK_SEARCH_PATHS:
            - "$(inherited)"
            - "$(SRCROOT)/../build/bin/iosSimulatorArm64/debugFramework"
            - "$(SRCROOT)/../build/bin/iosArm64/debugFramework"
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGNING_REQUIRED: "NO"
          CODE_SIGNING_ALLOWED: "NO"
        Release:
          FRAMEWORK_SEARCH_PATHS:
            - "$(inherited)"
            - "$(SRCROOT)/../build/bin/iosArm64/releaseFramework"
          CODE_SIGN_IDENTITY: "Apple Development"
          CODE_SIGNING_REQUIRED: "YES"
          CODE_SIGNING_ALLOWED: "YES"
          CODE_SIGN_STYLE: "Automatic"
    postBuildScripts:
      - name: Set Build Number from Git
        script: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $COMMIT_COUNT" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"

  CommCareUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CommCareUITests
        type: group
    dependencies:
      - target: CommCare
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.marshellis.commcare.ios.uitests
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        TEST_TARGET_NAME: CommCare
