package org.commcare.test

import org.javarosa.core.model.FormDef
import org.javarosa.core.model.data.DecimalData
import org.javarosa.core.model.data.GeoPointData
import org.javarosa.core.model.data.IAnswerData
import org.javarosa.core.model.data.IntegerData
import org.javarosa.core.model.data.SelectMultiData
import org.javarosa.core.model.data.SelectOneData
import org.javarosa.core.model.data.StringData
import org.javarosa.core.model.data.helper.Selection
import org.javarosa.form.api.FormEntryController
import org.javarosa.form.api.FormEntryModel
import org.javarosa.model.xform.DataModelSerializer
import org.javarosa.xform.util.XFormLoader
import org.javarosa.xml.createXmlSerializer
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Cross-platform form serialization tests. Loads forms, fills with answers,
 * serializes via the cross-platform DataModelSerializer, and compares against
 * golden files generated by the JVM oracle (XFormSerializingVisitor).
 *
 * Runs on both JVM and iOS to validate serialization parity.
 */
class FormSerializationCrossPlatformTest {

    private fun loadForm(resourcePath: String): FormDef {
        val bytes = TestResources.loadResource(resourcePath)
        return XFormLoader.loadForm(bytes)
    }

    private fun serializeForm(formDef: FormDef): String {
        val instance = formDef.getInstance()!!
        val serializer = createXmlSerializer()
        val dms = DataModelSerializer(serializer)
        dms.serialize(instance.getRoot())
        return serializer.toByteArray().decodeToString()
    }

    private fun loadGolden(name: String): String {
        return TestResources.loadResource("/golden/$name.expected.xml")
            .decodeToString().trim()
    }

    private fun normalizeXml(xml: String): String {
        return xml.trim()
            .replace(Regex("""<\?xml[^?]*\?>"""), "")
            .replace(Regex("""\s+xmlns(:\w+)?="[^"]*""""), "")
            .replace(Regex("""\s+(uiVersion|version|name)="[^"]*""""), "")
            .replace("\r\n", "\n")
            .replace("\r", "\n")
            .lines()
            .joinToString("\n") { it.trimEnd() }
            .trim()
    }

    private fun fillAndSerialize(
        resourcePath: String,
        answers: List<IAnswerData?>
    ): String {
        val formDef = loadForm(resourcePath)
        formDef.initialize(true, null)

        val model = FormEntryModel(formDef)
        val controller = FormEntryController(model)

        controller.stepToNextEvent()
        var answerIndex = 0

        while (model.getEvent() != FormEntryController.EVENT_END_OF_FORM) {
            if (model.getEvent() == FormEntryController.EVENT_QUESTION) {
                if (answerIndex < answers.size && answers[answerIndex] != null) {
                    val result = controller.answerQuestion(answers[answerIndex])
                    assertEquals(
                        FormEntryController.ANSWER_OK, result,
                        "Answer rejected at question $answerIndex"
                    )
                }
                answerIndex++
            }
            controller.stepToNextEvent()
        }

        return serializeForm(formDef)
    }

    private fun fillWithNavigation(
        resourcePath: String,
        navigate: (FormEntryModel, FormEntryController) -> Unit
    ): String {
        val formDef = loadForm(resourcePath)
        formDef.initialize(true, null)

        val model = FormEntryModel(formDef, FormEntryModel.REPEAT_STRUCTURE_LINEAR)
        val controller = FormEntryController(model)

        controller.stepToNextEvent()
        navigate(model, controller)

        return serializeForm(formDef)
    }

    // --- Empty Form Tests ---

    @Test
    fun testEmptyFormMatchesGolden() {
        val xml = fillAndSerialize(
            "/test_all_question_types.xml",
            listOf(null, null, null, null, null, null, null)
        )
        val golden = loadGolden("all_question_types_empty")
        assertEquals(normalizeXml(golden), normalizeXml(xml))
    }

    @Test
    fun testMultiSelectEmptyMatchesGolden() {
        val xml = fillAndSerialize(
            "/test_multi_select.xml",
            listOf(null, null, null)
        )
        val golden = loadGolden("multi_select_empty")
        assertEquals(normalizeXml(golden), normalizeXml(xml))
    }

    // --- Text and Basic Types ---

    @Test
    fun testTextOnlyAnswersMatchGolden() {
        val xml = fillAndSerialize(
            "/test_all_question_types.xml",
            listOf(
                StringData("John Doe"),
                IntegerData(30),
                DecimalData(72.5),
                null, // date
                null, // time
                SelectOneData(Selection("male")),
                null  // hobbies
            )
        )
        val golden = loadGolden("all_question_types_text_only")
        assertEquals(normalizeXml(golden), normalizeXml(xml))
    }

    @Test
    fun testStringDataSerializesCorrectly() {
        val xml = fillAndSerialize(
            "/test_all_question_types.xml",
            listOf(StringData("Hello World"), null, null, null, null, null, null)
        )
        assertTrue(xml.contains("<text_answer>Hello World</text_answer>"))
    }

    @Test
    fun testIntegerDataSerializesCorrectly() {
        val xml = fillAndSerialize(
            "/test_all_question_types.xml",
            listOf(null, IntegerData(42), null, null, null, null, null)
        )
        assertTrue(xml.contains("<integer_answer>42</integer_answer>"))
    }

    @Test
    fun testDecimalDataSerializesCorrectly() {
        val xml = fillAndSerialize(
            "/test_all_question_types.xml",
            listOf(null, null, DecimalData(3.14), null, null, null, null)
        )
        assertTrue(xml.contains("<decimal_answer>3.14</decimal_answer>"))
    }

    @Test
    fun testSelectOneSerializesCorrectly() {
        val xml = fillAndSerialize(
            "/test_all_question_types.xml",
            listOf(null, null, null, null, null, SelectOneData(Selection("female")), null)
        )
        assertTrue(xml.contains("<select_one_answer>female</select_one_answer>"))
    }

    // --- Calculations ---

    @Test
    fun testCalculationsMatchGolden() {
        val xml = fillAndSerialize(
            "/test_calculations.xml",
            listOf(
                IntegerData(5),
                DecimalData(10.0),
                DecimalData(5.0),
                StringData("World")
            )
        )
        val golden = loadGolden("calculations_basic")
        assertEquals(normalizeXml(golden), normalizeXml(xml))
    }

    @Test
    fun testCalculatedFieldsComputed() {
        val xml = fillAndSerialize(
            "/test_calculations.xml",
            listOf(
                IntegerData(5),
                DecimalData(10.0),
                DecimalData(5.0),
                StringData("World")
            )
        )
        assertTrue(xml.contains("<total>50</total>"), "total should be 5*10=50")
        assertTrue(xml.contains("<final_price>45</final_price>"), "final_price should be 50-5=45")
        assertTrue(xml.contains("<greeting>Hello World</greeting>"), "greeting should concat")
    }

    // --- GeoPoint ---

    @Test
    fun testGeoPointMatchesGolden() {
        val xml = fillAndSerialize(
            "/test_geopoint.xml",
            listOf(
                StringData("Office"),
                GeoPointData(doubleArrayOf(42.3601, -71.0589, 10.0, 5.0)),
                StringData("Main office location")
            )
        )
        val golden = loadGolden("geopoint_basic")
        assertEquals(normalizeXml(golden), normalizeXml(xml))
    }

    @Test
    fun testGeoPointFormat() {
        val xml = fillAndSerialize(
            "/test_geopoint.xml",
            listOf(
                StringData("Test"),
                GeoPointData(doubleArrayOf(42.3601, -71.0589, 10.0, 5.0)),
                null
            )
        )
        assertTrue(
            xml.contains("42.3601 -71.0589 10.0 5.0"),
            "GeoPoint should serialize as space-separated values"
        )
    }

    // --- Multi-Select ---

    @Test
    fun testMultiSelectMatchesGolden() {
        val xml = fillAndSerialize(
            "/test_multi_select.xml",
            listOf(
                SelectOneData(Selection("blue")),
                SelectMultiData(arrayListOf(Selection("fever"), Selection("cough"))),
                SelectOneData(Selection("moderate"))
            )
        )
        val golden = loadGolden("multi_select_basic")
        assertEquals(normalizeXml(golden), normalizeXml(xml))
    }

    @Test
    fun testMultiSelectSpaceSeparated() {
        val xml = fillAndSerialize(
            "/test_multi_select.xml",
            listOf(
                null,
                SelectMultiData(arrayListOf(Selection("fever"), Selection("cough"))),
                null
            )
        )
        assertTrue(
            xml.contains("<symptoms>fever cough</symptoms>"),
            "Multi-select should be space-separated"
        )
    }

    // --- Repeat Groups ---

    @Test
    fun testRepeatSkipMatchesGolden() {
        val xml = fillWithNavigation("/test_repeat_and_relevancy.xml") { model, controller ->
            while (model.getEvent() != FormEntryController.EVENT_END_OF_FORM) {
                controller.stepToNextEvent()
            }
        }
        val golden = loadGolden("repeat_skip")
        assertEquals(normalizeXml(golden), normalizeXml(xml))
    }

    // --- Constraints ---

    @Test
    fun testConstraintsValidMatchesGolden() {
        // Use step-by-step navigation (not field-list getQuestionPrompts) for
        // cross-platform compatibility — answer each question individually.
        val answers = listOf(
            IntegerData(25),
            StringData("Jane"),
            StringData("j@e.co")
        )
        val xml = fillWithNavigation("/test_field_list_constraints.xml") { model, controller ->
            var answerIdx = 0
            while (model.getEvent() != FormEntryController.EVENT_END_OF_FORM) {
                if (model.getEvent() == FormEntryController.EVENT_QUESTION && answerIdx < answers.size) {
                    controller.answerQuestion(model.getFormIndex(), answers[answerIdx])
                    answerIdx++
                }
                controller.stepToNextEvent()
            }
        }
        val golden = loadGolden("constraints_valid")
        assertEquals(normalizeXml(golden), normalizeXml(xml))
    }

    // --- Idempotency ---

    @Test
    fun testSerializationIdempotent() {
        val formDef = loadForm("/test_all_question_types.xml")
        formDef.initialize(true, null)
        val model = FormEntryModel(formDef)
        val controller = FormEntryController(model)

        controller.stepToNextEvent()
        while (model.getEvent() != FormEntryController.EVENT_END_OF_FORM) {
            if (model.getEvent() == FormEntryController.EVENT_QUESTION) {
                controller.answerQuestion(StringData("test"))
            }
            controller.stepToNextEvent()
        }

        val xml1 = serializeForm(formDef)
        val xml2 = serializeForm(formDef)
        assertEquals(xml1, xml2, "Serialization should be idempotent")
    }
}
