package org.commcare.test.parity

import org.commcare.test.TestResources
import org.javarosa.core.model.FormDef
import org.javarosa.core.model.data.DecimalData
import org.javarosa.core.model.data.GeoPointData
import org.javarosa.core.model.data.IAnswerData
import org.javarosa.core.model.data.IntegerData
import org.javarosa.core.model.data.SelectOneData
import org.javarosa.core.model.data.StringData
import org.javarosa.core.model.data.helper.Selection
import org.javarosa.form.api.FormEntryController
import org.javarosa.form.api.FormEntryModel
import org.javarosa.model.xform.DataModelSerializer
import org.javarosa.xform.util.XFormLoader
import org.javarosa.xml.createXmlSerializer
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Simulator parity tests — validates that cross-platform form serialization
 * produces identical output on both JVM and iOS by comparing against golden files.
 *
 * These tests run on BOTH platforms via:
 *   JVM:  ./gradlew :commcare-core:test --tests "*SimulatorParityTest*"
 *   iOS:  ./gradlew :commcare-core:iosSimulatorArm64Test --tests "*SimulatorParityTest*"
 *
 * Golden files are generated by the JVM oracle (XFormSerializingVisitor) in
 * app/src/jvmTest GoldenFileGenerator.
 */
class SimulatorParityTest {

    private fun loadForm(resourcePath: String): FormDef {
        val bytes = TestResources.loadResource(resourcePath)
        return XFormLoader.loadForm(bytes)
    }

    private fun serializeForm(formDef: FormDef): String {
        val instance = formDef.getInstance()!!
        val serializer = createXmlSerializer()
        val dms = DataModelSerializer(serializer)
        dms.serialize(instance.getRoot())
        return serializer.toByteArray().decodeToString()
    }

    private fun loadGolden(name: String): String {
        return TestResources.loadResource("/golden/$name.expected.xml")
            .decodeToString().trim()
    }

    private fun normalizeXml(xml: String): String {
        return xml.trim()
            .replace(Regex("""<\?xml[^?]*\?>"""), "")
            .replace(Regex("""\s+xmlns(:\w+)?="[^"]*""""), "")
            .replace(Regex("""\s+(uiVersion|version|name)="[^"]*""""), "")
            .replace(Regex("""&#(\d+);""")) { Char(it.groupValues[1].toInt()).toString() }
            .replace("\r\n", "\n")
            .replace("\r", "\n")
            .lines()
            .joinToString("\n") { it.trimEnd() }
            .trim()
    }

    private fun fillAndSerialize(
        resourcePath: String,
        answers: List<IAnswerData?>
    ): String {
        val formDef = loadForm(resourcePath)
        formDef.initialize(true, null)

        val model = FormEntryModel(formDef)
        val controller = FormEntryController(model)

        controller.stepToNextEvent()
        var answerIndex = 0

        while (model.getEvent() != FormEntryController.EVENT_END_OF_FORM) {
            if (model.getEvent() == FormEntryController.EVENT_QUESTION) {
                if (answerIndex < answers.size && answers[answerIndex] != null) {
                    val result = controller.answerQuestion(answers[answerIndex])
                    assertEquals(
                        FormEntryController.ANSWER_OK, result,
                        "Answer rejected at question $answerIndex"
                    )
                }
                answerIndex++
            }
            controller.stepToNextEvent()
        }

        return serializeForm(formDef)
    }

    // --- Test 1: Simple text form ---

    @Test
    fun testSimpleTextFormMatchesGolden() {
        val xml = fillAndSerialize(
            "/test_all_question_types.xml",
            listOf(
                StringData("John Doe"),
                IntegerData(30),
                DecimalData(72.5),
                null, // date
                null, // time
                SelectOneData(Selection("male")),
                null  // hobbies
            )
        )
        val golden = loadGolden("all_question_types_text_only")
        assertEquals(
            normalizeXml(golden), normalizeXml(xml),
            "Text form serialization must match golden file on both platforms"
        )
    }

    // --- Test 2: Date question (empty form with dates skipped) ---

    @Test
    fun testEmptyFormMatchesGolden() {
        val xml = fillAndSerialize(
            "/test_all_question_types.xml",
            listOf(null, null, null, null, null, null, null)
        )
        val golden = loadGolden("all_question_types_empty")
        assertEquals(
            normalizeXml(golden), normalizeXml(xml),
            "Empty form serialization must match golden file on both platforms"
        )
    }

    // --- Test 3: Select question ---

    @Test
    fun testSelectQuestionMatchesGolden() {
        val xml = fillAndSerialize(
            "/test_multi_select.xml",
            listOf(
                SelectOneData(Selection("blue")),
                null, // skip multi-select
                SelectOneData(Selection("moderate"))
            )
        )
        // Verify select values serialize correctly on both platforms
        assertTrue(
            xml.contains("<favorite_color>blue</favorite_color>"),
            "Select one should serialize value on both platforms"
        )
        assertTrue(
            xml.contains("<severity>moderate</severity>"),
            "Select one should serialize value on both platforms"
        )
    }

    // --- Test 4: Repeat group (skip all repeats) ---

    @Test
    fun testRepeatGroupMatchesGolden() {
        val formDef = loadForm("/test_repeat_and_relevancy.xml")
        formDef.initialize(true, null)

        val model = FormEntryModel(formDef, FormEntryModel.REPEAT_STRUCTURE_LINEAR)
        val controller = FormEntryController(model)

        controller.stepToNextEvent()
        while (model.getEvent() != FormEntryController.EVENT_END_OF_FORM) {
            controller.stepToNextEvent()
        }

        val xml = serializeForm(formDef)
        val golden = loadGolden("repeat_skip")
        assertEquals(
            normalizeXml(golden), normalizeXml(xml),
            "Repeat skip serialization must match golden file on both platforms"
        )
    }

    // --- Test 5: Calculated field ---

    @Test
    fun testCalculatedFieldMatchesGolden() {
        val xml = fillAndSerialize(
            "/test_calculations.xml",
            listOf(
                IntegerData(5),
                DecimalData(10.0),
                DecimalData(5.0),
                StringData("World")
            )
        )
        val golden = loadGolden("calculations_basic")
        assertEquals(
            normalizeXml(golden), normalizeXml(xml),
            "Calculation serialization must match golden file on both platforms"
        )
    }
}
